/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author Agnes-PC
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    
     controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        admin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        panel4 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        panel5 = new java.awt.Panel();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_bersihkan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        panel6 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        btn_Cari = new javax.swing.JButton();
        CbCariKategori = new javax.swing.JComboBox<>();
        panel7 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        panel8 = new java.awt.Panel();
        txtHarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(null);

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setLayout(null);

        admin.setBackground(new java.awt.Color(255, 255, 255));
        admin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel2.add(admin);
        admin.setBounds(90, 10, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Toko");
        panel2.add(jLabel4);
        jLabel4.setBounds(10, 20, 80, 15);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA BARANG");
        panel2.add(jLabel1);
        jLabel1.setBounds(210, 50, 230, 30);

        panel1.add(panel2);
        panel2.setBounds(10, 10, 630, 90);

        panel3.setBackground(new java.awt.Color(204, 204, 204));
        panel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nama Barang");
        panel3.add(jLabel6);
        jLabel6.setBounds(20, 100, 80, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Kode Barang");
        panel3.add(jLabel8);
        jLabel8.setBounds(20, 10, 80, 15);

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panel3.add(txtNama);
        txtNama.setBounds(20, 130, 250, 40);

        txtKode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });
        panel3.add(txtKode);
        txtKode.setBounds(20, 40, 250, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Kategori Barang");
        panel3.add(jLabel9);
        jLabel9.setBounds(20, 180, 110, 15);

        cbKategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Tulis", "Alamat Rumah Tangga", "Barang Lain" }));
        panel3.add(cbKategori);
        cbKategori.setBounds(20, 210, 250, 40);

        panel1.add(panel3);
        panel3.setBounds(10, 110, 310, 270);

        panel4.setBackground(new java.awt.Color(204, 204, 255));
        panel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Packaging");
        panel4.add(jLabel5);
        jLabel5.setBounds(20, 10, 100, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Harga");
        panel4.add(jLabel7);
        jLabel7.setBounds(20, 100, 80, 15);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panel4.add(jTextField3);
        jTextField3.setBounds(20, 130, 250, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack" }));
        panel4.add(jComboBox2);
        jComboBox2.setBounds(20, 40, 250, 40);

        panel1.add(panel4);
        panel4.setBounds(330, 110, 0, 0);

        panel5.setBackground(new java.awt.Color(153, 153, 153));
        panel5.setLayout(null);

        btn_simpan.setBackground(new java.awt.Color(0, 0, 0));
        btn_simpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        panel5.add(btn_simpan);
        btn_simpan.setBounds(30, 10, 90, 30);

        btn_ubah.setBackground(new java.awt.Color(0, 0, 0));
        btn_ubah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        panel5.add(btn_ubah);
        btn_ubah.setBounds(150, 10, 90, 30);

        btn_bersihkan.setBackground(new java.awt.Color(0, 0, 0));
        btn_bersihkan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_bersihkan.setForeground(new java.awt.Color(255, 255, 255));
        btn_bersihkan.setText("Bersihkan");
        btn_bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihkanActionPerformed(evt);
            }
        });
        panel5.add(btn_bersihkan);
        btn_bersihkan.setBounds(270, 10, 100, 30);

        btn_hapus.setBackground(new java.awt.Color(0, 0, 0));
        btn_hapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        panel5.add(btn_hapus);
        btn_hapus.setBounds(400, 10, 90, 30);

        btn_keluar.setBackground(new java.awt.Color(0, 0, 0));
        btn_keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        panel5.add(btn_keluar);
        btn_keluar.setBounds(520, 10, 80, 30);

        panel1.add(panel5);
        panel5.setBounds(10, 390, 630, 50);

        panel6.setBackground(new java.awt.Color(153, 153, 153));
        panel6.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pencarian Berdasarkan Kategori Makanan");
        panel6.add(jLabel3);
        jLabel3.setBounds(0, 10, 260, 20);

        btn_Cari.setBackground(new java.awt.Color(0, 0, 0));
        btn_Cari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Cari.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cari.setText("Cari");
        btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CariActionPerformed(evt);
            }
        });
        panel6.add(btn_Cari);
        btn_Cari.setBounds(510, 10, 80, 30);

        CbCariKategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CbCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Tulis", "Alat Rumah Tangga", "Barang Lain" }));
        CbCariKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCariKategoriActionPerformed(evt);
            }
        });
        panel6.add(CbCariKategori);
        CbCariKategori.setBounds(290, 10, 190, 30);

        panel1.add(panel6);
        panel6.setBounds(10, 450, 630, 50);

        panel7.setBackground(new java.awt.Color(0, 0, 0));
        panel7.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
            tblData.getColumnModel().getColumn(1).setResizable(false);
            tblData.getColumnModel().getColumn(2).setResizable(false);
            tblData.getColumnModel().getColumn(3).setResizable(false);
            tblData.getColumnModel().getColumn(4).setResizable(false);
        }

        panel7.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 610, 130);

        panel1.add(panel7);
        panel7.setBounds(10, 510, 630, 150);

        panel8.setBackground(new java.awt.Color(204, 204, 204));
        panel8.setLayout(null);

        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panel8.add(txtHarga);
        txtHarga.setBounds(20, 130, 250, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Jenis Packaging");
        panel8.add(jLabel13);
        jLabel13.setBounds(20, 10, 110, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Harga");
        panel8.add(jLabel11);
        jLabel11.setBounds(20, 100, 80, 15);

        cbJenis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Pcs", " " }));
        panel8.add(cbJenis);
        cbJenis.setBounds(20, 40, 250, 40);

        panel1.add(panel8);
        panel8.setBounds(330, 110, 310, 270);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 650, 680);

        setSize(new java.awt.Dimension(665, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
       ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihkanActionPerformed
        // TODO add your handling code here:
        ctoko.Reset();
    }//GEN-LAST:event_btn_bersihkanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        ctoko.Ubah();
        ctoko.isiTable(); 
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CariActionPerformed
        // TODO add your handling code here:
        ctoko.CariKategori();
        ctoko.isiTableCariKategori();
    }//GEN-LAST:event_btn_CariActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
         ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1)
        {
            txtKode.setText(tblData.getValueAt(baris, 0).toString());
            txtNama.setText((String) tblData.getValueAt(baris, 1));
            cbKategori.setSelectedItem(tblData.getValueAt(baris, 2).toString());
            cbJenis.setSelectedItem(tblData.getValueAt(baris, 3).toString());
            txtHarga.setText(tblData.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user = login.user;
        admin.setText(" "+user);
    }//GEN-LAST:event_formWindowOpened

    private void CbCariKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCariKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCariKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbCariKategori;
    private javax.swing.JLabel admin;
    private javax.swing.JButton btn_Cari;
    private javax.swing.JButton btn_bersihkan;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
    public JTextField getTxtKode(){
        return txtKode;
    }
    public JTextField getTxtNama(){
        return txtNama;
    }
    public JTextField getTxtHarga(){
        return txtHarga;
    }
    public JComboBox getCbKategori(){
        return cbKategori;
    }
    public JComboBox getCbJenis(){
        return cbJenis;
    }
    public JComboBox getCbCariKategori(){
        return CbCariKategori;
    }
    public JButton getButtonHapus(){
        return btn_hapus;
    }
    
    public JButton getButtonBersih(){
        return btn_bersihkan;
    }
    public JButton getButtonSimpan(){
        return btn_simpan;
    }
    public JButton getButtonUbah(){
        return btn_ubah;
    }
    public JButton getButtonKeluar(){
        return btn_keluar;
    }
    public JTable getTableData(){
        return tblData;
    }
    public void setAdmin (String Admin) {
        admin.setText(Admin);
    }

    }
